### ISSUE TITLE
Debugability

### ISSUE THREAD

**Issue by flah00** [bitnami/nami#33]
I'm creating a new image, based on bitnami/bitnami-docker-redmine, because I'm customizing my install of the helm chart `stable/redmine`. I've successfully built my image, but I'm running into issues ... And I'm finding it quite a challenge to debug this system. 

1. It would be helpful if the configuration files for nami were in the application directory or `/`
    * Putting them in `~/.nami` is counterintuitive, since every other relevant file is already in `/opt/bitnami/redmine` or `/`
1. Documentation regarding nami would be helpful
    * What is the analog of sh `set -x`?
    * How does one go about obtaining a shell, at a breakpoint, in the nami world?

**Comment by juamedgod** [comment]
>It would be helpful if the configuration files for nami were in the application directory or /
>Putting them in ~/.nami is counterintuitive, since every other relevant file is already in /opt/bitnami/redmine or /

The registry is common to all installed modules, which may have different installation directories, that is why it is not under /opt/bitnami/redmine.

It is located under ~/.nami because different users may have different sets of modules installed.

> Documentation regarding nami would be helpful

We have some documentation under the docs directory:

https://github.com/bitnami/nami/blob/master/docs/Nami.md

>What is the analog of sh set -x?

It is not exactly like sh -x but you can increase the debug level with the --log-level flag:

https://github.com/bitnami/nami/blob/master/docs/Nami.md#log

>How does one go about obtaining a shell, at a breakpoint, in the nami world?

We do not support breakpoints. About obtaining a shell, you can open an interactive console:

https://github.com/bitnami/nami/blob/master/docs/Nami.md#interactive-console

**Comment by flah00** [comment]
Thanks for the quick reply! 

> We have some documentation

I found the document a bit impenetrable, a mishmash of developer and operator manual. It's a pretty dense document, when you're trying to figure out the best way to debug in a distributed environment. A table of contents would go a long way, in such a large document.

Ultimately, I found it very difficult, as someone new to the project, to quickly grasp the actions nami was taking, where its configuration files were, and how to debug it. I feel like a document which offers the uninitiated a crash course would be very helpful.

> It is not exactly like sh -x but you can increase the debug level with the --log-level flag

The interaction between `nami`, `/app-entrypoint.sh`, `/init.sh`, `/run.sh`, and `/*.json` doesn't seem to have a documentation home either... So, there was a lot of working backwards. It took me longer than I would've liked, to learn about the `NAMI_DEBUG` env var.

> you can open an interactive console

Interesting, thanks for the tip!

**Comment by juamedgod** [comment]
Thanks for your feedback!

>It seems like a central organizing file, which defines installation and post installation steps, shouldn't be stored in a dot directory. It should follow conventions, perhaps using /etc as its home for config files?

Its intention is not really to be a configurations directory but more as a registry of installed packages (which includes a copy of the package definition). Moving to a global directory such as /etc/ would make the registry shared among all users which would go against the idea of allowing different users having their own set of modules.

In any case, the project is still under development and adapting to its requirements (its main usage nowadays is to be used in containers) so this may change to better suit that. We will certainly take your feedback into account.

>I found the document a bit impenetrable, a mishmash of developer and operator manual. It's pretty dense, when you're trying to figure out the best way to debug in a distributed environment. A table of contents would go a long way, in such a large file.

Yes, you are right. The documentation is more focused on module developers. And definitely a table of contents can be really useful.

>The interaction between nami, /app-entrypoint.sh, /init.sh, /run.sh, and /*.json doesn't seem to have a documentation home either... So, there was a lot of working backwards. It took me longer than I would've liked, to learn about the NAMI_DEBUG env var.

The design of how containers make use of nami is handled by a different team. I have forwarded your comments so they can improve on their side.
